services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: 'sh -c "trap : TERM INT; sleep 86400 & wait"'
#    command: python3 -m deflakyzavr --config ugc_config.cfg
    volumes:
      - .:/deflakyzavr
